# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'energydomain_dialog.ui'
#
# Created: Sat Jul 19 20:42:24 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EnergyDomainDialog(object):
    def setupUi(self, EnergyDomainDialog):
        EnergyDomainDialog.setObjectName(_fromUtf8("EnergyDomainDialog"))
        EnergyDomainDialog.resize(400, 300)
        self.CloseButton = QtGui.QPushButton(EnergyDomainDialog)
        self.CloseButton.setGeometry(QtCore.QRect(280, 270, 114, 32))
        self.CloseButton.setAutoDefault(False)
        self.CloseButton.setObjectName(_fromUtf8("CloseButton"))
        self.groupBox = QtGui.QGroupBox(EnergyDomainDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 191, 241))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.checkBox_ordering = QtGui.QCheckBox(self.groupBox)
        self.checkBox_ordering.setGeometry(QtCore.QRect(10, 120, 87, 20))
        self.checkBox_ordering.setChecked(True)
        self.checkBox_ordering.setObjectName(_fromUtf8("checkBox_ordering"))
        self.comboBox_ordering = QtGui.QComboBox(self.groupBox)
        self.comboBox_ordering.setGeometry(QtCore.QRect(10, 140, 141, 26))
        self.comboBox_ordering.setObjectName(_fromUtf8("comboBox_ordering"))
        self.comboBox_ordering.addItem(_fromUtf8(""))
        self.comboBox_ordering.addItem(_fromUtf8(""))
        self.comboBox_ordering.addItem(_fromUtf8(""))
        self.comboBox_ordering.addItem(_fromUtf8(""))
        self.lineEdit_ordering = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_ordering.setEnabled(False)
        self.lineEdit_ordering.setGeometry(QtCore.QRect(134, 170, 50, 21))
        self.lineEdit_ordering.setObjectName(_fromUtf8("lineEdit_ordering"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(81, 170, 51, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.GetEigenButton = QtGui.QPushButton(self.groupBox)
        self.GetEigenButton.setGeometry(QtCore.QRect(80, 200, 114, 32))
        self.GetEigenButton.setAutoDefault(False)
        self.GetEigenButton.setObjectName(_fromUtf8("GetEigenButton"))
        self.lineEdit_dim = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_dim.setGeometry(QtCore.QRect(70, 32, 41, 21))
        self.lineEdit_dim.setObjectName(_fromUtf8("lineEdit_dim"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 32, 60, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEdit_qdomain = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_qdomain.setGeometry(QtCore.QRect(40, 64, 71, 21))
        self.lineEdit_qdomain.setObjectName(_fromUtf8("lineEdit_qdomain"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 96, 16, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 64, 16, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit_pdomain = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_pdomain.setGeometry(QtCore.QRect(40, 96, 72, 21))
        self.lineEdit_pdomain.setObjectName(_fromUtf8("lineEdit_pdomain"))
        self.comboBox_SelectAlgorism = QtGui.QComboBox(EnergyDomainDialog)
        self.comboBox_SelectAlgorism.setGeometry(QtCore.QRect(10, 10, 381, 26))
        self.comboBox_SelectAlgorism.setObjectName(_fromUtf8("comboBox_SelectAlgorism"))
        self.comboBox_SelectAlgorism.addItem(_fromUtf8(""))
        self.comboBox_SelectAlgorism.addItem(_fromUtf8(""))
        self.comboBox_SelectAlgorism.addItem(_fromUtf8(""))
        self.groupBox_2 = QtGui.QGroupBox(EnergyDomainDialog)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setGeometry(QtCore.QRect(210, 30, 181, 151))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.lineEdit_hsmqrange = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_hsmqrange.setGeometry(QtCore.QRect(30, 60, 71, 21))
        self.lineEdit_hsmqrange.setObjectName(_fromUtf8("lineEdit_hsmqrange"))
        self.lineEdit_hsmprange = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_hsmprange.setGeometry(QtCore.QRect(30, 90, 71, 21))
        self.lineEdit_hsmprange.setObjectName(_fromUtf8("lineEdit_hsmprange"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 20, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 90, 21, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 30, 91, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit_hsmgrid = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_hsmgrid.setGeometry(QtCore.QRect(100, 30, 61, 21))
        self.lineEdit_hsmgrid.setObjectName(_fromUtf8("lineEdit_hsmgrid"))
        self.drawButton = QtGui.QPushButton(self.groupBox_2)
        self.drawButton.setGeometry(QtCore.QRect(70, 120, 114, 32))
        self.drawButton.setAutoDefault(False)
        self.drawButton.setObjectName(_fromUtf8("drawButton"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 126, 21, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEdit_QuantumNumber = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_QuantumNumber.setGeometry(QtCore.QRect(25, 123, 31, 21))
        self.lineEdit_QuantumNumber.setObjectName(_fromUtf8("lineEdit_QuantumNumber"))
        self.groupBox_3 = QtGui.QGroupBox(EnergyDomainDialog)
        self.groupBox_3.setEnabled(False)
        self.groupBox_3.setGeometry(QtCore.QRect(210, 180, 181, 91))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.eigenvaluesButton = QtGui.QPushButton(self.groupBox_3)
        self.eigenvaluesButton.setGeometry(QtCore.QRect(70, 30, 114, 32))
        self.eigenvaluesButton.setAutoDefault(False)
        self.eigenvaluesButton.setObjectName(_fromUtf8("eigenvaluesButton"))

        self.retranslateUi(EnergyDomainDialog)
        QtCore.QObject.connect(self.CloseButton, QtCore.SIGNAL(_fromUtf8("clicked()")), EnergyDomainDialog.reject)
        QtCore.QObject.connect(self.lineEdit_QuantumNumber, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.drawButton.animateClick)
        QtCore.QObject.connect(self.lineEdit_hsmprange, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.drawButton.animateClick)
        QtCore.QObject.connect(self.lineEdit_hsmqrange, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.drawButton.animateClick)
        QtCore.QObject.connect(self.lineEdit_hsmgrid, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.drawButton.animateClick)
        QtCore.QObject.connect(self.checkBox_ordering, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_ordering.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(EnergyDomainDialog)
        EnergyDomainDialog.setTabOrder(self.comboBox_SelectAlgorism, self.lineEdit_dim)
        EnergyDomainDialog.setTabOrder(self.lineEdit_dim, self.lineEdit_qdomain)
        EnergyDomainDialog.setTabOrder(self.lineEdit_qdomain, self.lineEdit_pdomain)
        EnergyDomainDialog.setTabOrder(self.lineEdit_pdomain, self.checkBox_ordering)
        EnergyDomainDialog.setTabOrder(self.checkBox_ordering, self.comboBox_ordering)
        EnergyDomainDialog.setTabOrder(self.comboBox_ordering, self.lineEdit_ordering)
        EnergyDomainDialog.setTabOrder(self.lineEdit_ordering, self.GetEigenButton)
        EnergyDomainDialog.setTabOrder(self.GetEigenButton, self.lineEdit_hsmgrid)
        EnergyDomainDialog.setTabOrder(self.lineEdit_hsmgrid, self.lineEdit_hsmqrange)
        EnergyDomainDialog.setTabOrder(self.lineEdit_hsmqrange, self.lineEdit_hsmprange)
        EnergyDomainDialog.setTabOrder(self.lineEdit_hsmprange, self.lineEdit_QuantumNumber)
        EnergyDomainDialog.setTabOrder(self.lineEdit_QuantumNumber, self.drawButton)
        EnergyDomainDialog.setTabOrder(self.drawButton, self.CloseButton)

    def retranslateUi(self, EnergyDomainDialog):
        EnergyDomainDialog.setWindowTitle(_translate("EnergyDomainDialog", "Dialog", None))
        self.CloseButton.setText(_translate("EnergyDomainDialog", "Close", None))
        self.groupBox.setTitle(_translate("EnergyDomainDialog", "Quantum system setting", None))
        self.checkBox_ordering.setText(_translate("EnergyDomainDialog", "ordering", None))
        self.comboBox_ordering.setItemText(0, _translate("EnergyDomainDialog", "ref. integ. Ham.", None))
        self.comboBox_ordering.setItemText(1, _translate("EnergyDomainDialog", "energy levels", None))
        self.comboBox_ordering.setItemText(2, _translate("EnergyDomainDialog", "q-vari", None))
        self.comboBox_ordering.setItemText(3, _translate("EnergyDomainDialog", "p-vari", None))
        self.label_8.setText(_translate("EnergyDomainDialog", "center:", None))
        self.GetEigenButton.setText(_translate("EnergyDomainDialog", "get eigen", None))
        self.lineEdit_dim.setText(_translate("EnergyDomainDialog", "50", None))
        self.label.setText(_translate("EnergyDomainDialog", "Hil. dim.", None))
        self.label_3.setText(_translate("EnergyDomainDialog", "p:", None))
        self.label_2.setText(_translate("EnergyDomainDialog", "q:", None))
        self.comboBox_SelectAlgorism.setItemText(0, _translate("EnergyDomainDialog", "Quantum Mapping (SplitOperator)", None))
        self.comboBox_SelectAlgorism.setItemText(1, _translate("EnergyDomainDialog", "Hamiltonian (PositionBase)", None))
        self.comboBox_SelectAlgorism.setItemText(2, _translate("EnergyDomainDialog", "Hamiltonian (HarmonicBase)", None))
        self.groupBox_2.setTitle(_translate("EnergyDomainDialog", "Husimi setting", None))
        self.label_4.setText(_translate("EnergyDomainDialog", "vq:", None))
        self.label_6.setText(_translate("EnergyDomainDialog", "vp:", None))
        self.label_7.setText(_translate("EnergyDomainDialog", "grid (col,row)", None))
        self.lineEdit_hsmgrid.setText(_translate("EnergyDomainDialog", "50,50", None))
        self.drawButton.setText(_translate("EnergyDomainDialog", "Draw ", None))
        self.label_5.setText(_translate("EnergyDomainDialog", "n:", None))
        self.lineEdit_QuantumNumber.setText(_translate("EnergyDomainDialog", "0", None))
        self.groupBox_3.setTitle(_translate("EnergyDomainDialog", "eigenvalues", None))
        self.eigenvaluesButton.setText(_translate("EnergyDomainDialog", "eigen values", None))

