# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'energydomain_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EnergyDomainDialog(object):
    def setupUi(self, EnergyDomainDialog):
        EnergyDomainDialog.setObjectName("EnergyDomainDialog")
        EnergyDomainDialog.resize(440, 348)
        self.CloseButton = QtWidgets.QPushButton(EnergyDomainDialog)
        self.CloseButton.setGeometry(QtCore.QRect(320, 310, 114, 32))
        self.CloseButton.setAutoDefault(False)
        self.CloseButton.setObjectName("CloseButton")
        self.groupBox_System = QtWidgets.QGroupBox(EnergyDomainDialog)
        self.groupBox_System.setGeometry(QtCore.QRect(10, 30, 191, 151))
        self.groupBox_System.setObjectName("groupBox_System")
        self.GetEigenButton = QtWidgets.QPushButton(self.groupBox_System)
        self.GetEigenButton.setGeometry(QtCore.QRect(100, 120, 91, 32))
        self.GetEigenButton.setAutoDefault(False)
        self.GetEigenButton.setObjectName("GetEigenButton")
        self.lineEdit_dim = QtWidgets.QLineEdit(self.groupBox_System)
        self.lineEdit_dim.setGeometry(QtCore.QRect(70, 32, 41, 21))
        self.lineEdit_dim.setObjectName("lineEdit_dim")
        self.label = QtWidgets.QLabel(self.groupBox_System)
        self.label.setGeometry(QtCore.QRect(10, 32, 60, 16))
        self.label.setObjectName("label")
        self.lineEdit_qdomain = QtWidgets.QLineEdit(self.groupBox_System)
        self.lineEdit_qdomain.setGeometry(QtCore.QRect(40, 64, 71, 21))
        self.lineEdit_qdomain.setObjectName("lineEdit_qdomain")
        self.label_3 = QtWidgets.QLabel(self.groupBox_System)
        self.label_3.setGeometry(QtCore.QRect(10, 96, 16, 16))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_System)
        self.label_2.setGeometry(QtCore.QRect(10, 64, 16, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_pdomain = QtWidgets.QLineEdit(self.groupBox_System)
        self.lineEdit_pdomain.setGeometry(QtCore.QRect(40, 96, 72, 21))
        self.lineEdit_pdomain.setObjectName("lineEdit_pdomain")
        self.comboBox_SelectAlgorism = QtWidgets.QComboBox(EnergyDomainDialog)
        self.comboBox_SelectAlgorism.setGeometry(QtCore.QRect(10, 10, 381, 26))
        self.comboBox_SelectAlgorism.setObjectName("comboBox_SelectAlgorism")
        self.comboBox_SelectAlgorism.addItem("")
        self.comboBox_SelectAlgorism.addItem("")
        self.comboBox_SelectAlgorism.addItem("")
        self.groupBox_Hsm = QtWidgets.QGroupBox(EnergyDomainDialog)
        self.groupBox_Hsm.setEnabled(False)
        self.groupBox_Hsm.setGeometry(QtCore.QRect(210, 30, 221, 271))
        self.groupBox_Hsm.setObjectName("groupBox_Hsm")
        self.lineEdit_hsmqrange = QtWidgets.QLineEdit(self.groupBox_Hsm)
        self.lineEdit_hsmqrange.setGeometry(QtCore.QRect(50, 60, 71, 21))
        self.lineEdit_hsmqrange.setObjectName("lineEdit_hsmqrange")
        self.lineEdit_hsmprange = QtWidgets.QLineEdit(self.groupBox_Hsm)
        self.lineEdit_hsmprange.setGeometry(QtCore.QRect(50, 90, 71, 21))
        self.lineEdit_hsmprange.setObjectName("lineEdit_hsmprange")
        self.label_4 = QtWidgets.QLabel(self.groupBox_Hsm)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 20, 16))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_Hsm)
        self.label_6.setGeometry(QtCore.QRect(20, 90, 21, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_Hsm)
        self.label_7.setGeometry(QtCore.QRect(10, 30, 91, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_hsmgrid = QtWidgets.QLineEdit(self.groupBox_Hsm)
        self.lineEdit_hsmgrid.setGeometry(QtCore.QRect(120, 30, 61, 21))
        self.lineEdit_hsmgrid.setObjectName("lineEdit_hsmgrid")
        self.drawButton = QtWidgets.QPushButton(self.groupBox_Hsm)
        self.drawButton.setGeometry(QtCore.QRect(110, 120, 114, 32))
        self.drawButton.setAutoDefault(False)
        self.drawButton.setObjectName("drawButton")
        self.label_5 = QtWidgets.QLabel(self.groupBox_Hsm)
        self.label_5.setGeometry(QtCore.QRect(29, 121, 21, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_QuantumNumber = QtWidgets.QLineEdit(self.groupBox_Hsm)
        self.lineEdit_QuantumNumber.setGeometry(QtCore.QRect(50, 120, 61, 21))
        self.lineEdit_QuantumNumber.setObjectName("lineEdit_QuantumNumber")
        self.label_9 = QtWidgets.QLabel(self.groupBox_Hsm)
        self.label_9.setGeometry(QtCore.QRect(10, 190, 101, 16))
        self.label_9.setObjectName("label_9")
        self.lineEdit_contourlinspace = QtWidgets.QLineEdit(self.groupBox_Hsm)
        self.lineEdit_contourlinspace.setGeometry(QtCore.QRect(110, 190, 101, 21))
        self.lineEdit_contourlinspace.setObjectName("lineEdit_contourlinspace")
        self.eigenvaluesButton = QtWidgets.QPushButton(self.groupBox_Hsm)
        self.eigenvaluesButton.setGeometry(QtCore.QRect(110, 230, 114, 32))
        self.eigenvaluesButton.setAutoDefault(False)
        self.eigenvaluesButton.setObjectName("eigenvaluesButton")
        self.checkBox_withcontour = QtWidgets.QCheckBox(self.groupBox_Hsm)
        self.checkBox_withcontour.setEnabled(False)
        self.checkBox_withcontour.setGeometry(QtCore.QRect(10, 160, 161, 20))
        self.checkBox_withcontour.setChecked(False)
        self.checkBox_withcontour.setObjectName("checkBox_withcontour")
        self.groupBox_ordering = QtWidgets.QGroupBox(EnergyDomainDialog)
        self.groupBox_ordering.setEnabled(False)
        self.groupBox_ordering.setGeometry(QtCore.QRect(10, 180, 191, 121))
        self.groupBox_ordering.setObjectName("groupBox_ordering")
        self.orderingButton = QtWidgets.QPushButton(self.groupBox_ordering)
        self.orderingButton.setGeometry(QtCore.QRect(100, 90, 91, 32))
        self.orderingButton.setAutoDefault(False)
        self.orderingButton.setObjectName("orderingButton")
        self.comboBox_ordering = QtWidgets.QComboBox(self.groupBox_ordering)
        self.comboBox_ordering.setGeometry(QtCore.QRect(0, 20, 141, 26))
        self.comboBox_ordering.setObjectName("comboBox_ordering")
        self.comboBox_ordering.addItem("")
        self.comboBox_ordering.addItem("")
        self.comboBox_ordering.addItem("")
        self.comboBox_ordering.addItem("")
        self.label_8 = QtWidgets.QLabel(self.groupBox_ordering)
        self.label_8.setGeometry(QtCore.QRect(70, 60, 51, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_ordering = QtWidgets.QLineEdit(self.groupBox_ordering)
        self.lineEdit_ordering.setEnabled(False)
        self.lineEdit_ordering.setGeometry(QtCore.QRect(120, 60, 51, 21))
        self.lineEdit_ordering.setObjectName("lineEdit_ordering")
        self.orderingButton.raise_()
        self.comboBox_ordering.raise_()
        self.label_8.raise_()
        self.lineEdit_ordering.raise_()
        self.lineEdit_ordering.raise_()

        self.retranslateUi(EnergyDomainDialog)
        self.CloseButton.clicked.connect(EnergyDomainDialog.reject)
        self.lineEdit_QuantumNumber.returnPressed.connect(self.drawButton.animateClick)
        self.lineEdit_hsmprange.returnPressed.connect(self.drawButton.animateClick)
        self.lineEdit_hsmqrange.returnPressed.connect(self.drawButton.animateClick)
        self.lineEdit_hsmgrid.returnPressed.connect(self.drawButton.animateClick)
        self.lineEdit_dim.returnPressed.connect(self.GetEigenButton.animateClick)
        self.lineEdit_pdomain.returnPressed.connect(self.GetEigenButton.animateClick)
        self.lineEdit_qdomain.returnPressed.connect(self.GetEigenButton.animateClick)
        self.lineEdit_contourlinspace.returnPressed.connect(self.drawButton.animateClick)
        QtCore.QMetaObject.connectSlotsByName(EnergyDomainDialog)
        EnergyDomainDialog.setTabOrder(self.comboBox_SelectAlgorism, self.lineEdit_dim)
        EnergyDomainDialog.setTabOrder(self.lineEdit_dim, self.lineEdit_qdomain)
        EnergyDomainDialog.setTabOrder(self.lineEdit_qdomain, self.lineEdit_pdomain)
        EnergyDomainDialog.setTabOrder(self.lineEdit_pdomain, self.comboBox_ordering)
        EnergyDomainDialog.setTabOrder(self.comboBox_ordering, self.GetEigenButton)
        EnergyDomainDialog.setTabOrder(self.GetEigenButton, self.lineEdit_hsmgrid)
        EnergyDomainDialog.setTabOrder(self.lineEdit_hsmgrid, self.lineEdit_hsmqrange)
        EnergyDomainDialog.setTabOrder(self.lineEdit_hsmqrange, self.lineEdit_hsmprange)
        EnergyDomainDialog.setTabOrder(self.lineEdit_hsmprange, self.lineEdit_QuantumNumber)
        EnergyDomainDialog.setTabOrder(self.lineEdit_QuantumNumber, self.drawButton)
        EnergyDomainDialog.setTabOrder(self.drawButton, self.CloseButton)

    def retranslateUi(self, EnergyDomainDialog):
        _translate = QtCore.QCoreApplication.translate
        EnergyDomainDialog.setWindowTitle(_translate("EnergyDomainDialog", "Dialog"))
        self.CloseButton.setText(_translate("EnergyDomainDialog", "Close"))
        self.groupBox_System.setTitle(_translate("EnergyDomainDialog", "Quantum system setting"))
        self.GetEigenButton.setText(_translate("EnergyDomainDialog", "get eigen"))
        self.lineEdit_dim.setText(_translate("EnergyDomainDialog", "50"))
        self.label.setText(_translate("EnergyDomainDialog", "Hil. dim."))
        self.label_3.setText(_translate("EnergyDomainDialog", "p:"))
        self.label_2.setText(_translate("EnergyDomainDialog", "q:"))
        self.comboBox_SelectAlgorism.setItemText(0, _translate("EnergyDomainDialog", "Quantum Mapping (SplitOperator)"))
        self.comboBox_SelectAlgorism.setItemText(1, _translate("EnergyDomainDialog", "Hamiltonian (PositionBase)"))
        self.comboBox_SelectAlgorism.setItemText(2, _translate("EnergyDomainDialog", "Hamiltonian (HarmonicBase)"))
        self.groupBox_Hsm.setTitle(_translate("EnergyDomainDialog", "figure setting"))
        self.label_4.setText(_translate("EnergyDomainDialog", "vq:"))
        self.label_6.setText(_translate("EnergyDomainDialog", "vp:"))
        self.label_7.setText(_translate("EnergyDomainDialog", "grid (col,row)"))
        self.lineEdit_hsmgrid.setText(_translate("EnergyDomainDialog", "50,50"))
        self.drawButton.setText(_translate("EnergyDomainDialog", "Draw "))
        self.label_5.setText(_translate("EnergyDomainDialog", "n:"))
        self.lineEdit_QuantumNumber.setText(_translate("EnergyDomainDialog", "0"))
        self.label_9.setText(_translate("EnergyDomainDialog", "min, max, num"))
        self.lineEdit_contourlinspace.setText(_translate("EnergyDomainDialog", "0,1,10"))
        self.eigenvaluesButton.setText(_translate("EnergyDomainDialog", "eigen values"))
        self.checkBox_withcontour.setText(_translate("EnergyDomainDialog", "with energy contour"))
        self.groupBox_ordering.setTitle(_translate("EnergyDomainDialog", "ordering"))
        self.orderingButton.setText(_translate("EnergyDomainDialog", "ordering"))
        self.comboBox_ordering.setItemText(0, _translate("EnergyDomainDialog", "ref. integ. Ham."))
        self.comboBox_ordering.setItemText(1, _translate("EnergyDomainDialog", "energy levels"))
        self.comboBox_ordering.setItemText(2, _translate("EnergyDomainDialog", "q-vari"))
        self.comboBox_ordering.setItemText(3, _translate("EnergyDomainDialog", "p-vari"))
        self.label_8.setText(_translate("EnergyDomainDialog", "center:"))

