# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maindesign.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1005, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(880, 630, 114, 32))
        self.closeButton.setObjectName("closeButton")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(600, 0, 20, 661))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.orbitsGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.orbitsGroupBox.setGeometry(QtCore.QRect(630, 0, 351, 241))
        self.orbitsGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.orbitsGroupBox.setObjectName("orbitsGroupBox")
        self.plotButton = QtWidgets.QPushButton(self.orbitsGroupBox)
        self.plotButton.setGeometry(QtCore.QRect(240, 110, 114, 32))
        self.plotButton.setObjectName("plotButton")
        self.comboBox_Select_Init = QtWidgets.QComboBox(self.orbitsGroupBox)
        self.comboBox_Select_Init.setEnabled(True)
        self.comboBox_Select_Init.setGeometry(QtCore.QRect(121, 20, 111, 26))
        self.comboBox_Select_Init.setAutoFillBackground(False)
        self.comboBox_Select_Init.setMinimumContentsLength(0)
        self.comboBox_Select_Init.setObjectName("comboBox_Select_Init")
        self.comboBox_Select_Init.addItem("")
        self.comboBox_Select_Init.addItem("")
        self.comboBox_Select_Init.addItem("")
        self.comboBox_Select_Init.addItem("")
        self.comboBox_Select_Init.addItem("")
        self.label_7 = QtWidgets.QLabel(self.orbitsGroupBox)
        self.label_7.setGeometry(QtCore.QRect(14, 23, 111, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.orbitsGroupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 140, 211, 20))
        self.label_8.setObjectName("label_8")
        self.itaration_lineEdit = QtWidgets.QLineEdit(self.orbitsGroupBox)
        self.itaration_lineEdit.setGeometry(QtCore.QRect(280, 80, 51, 20))
        self.itaration_lineEdit.setObjectName("itaration_lineEdit")
        self.label = QtWidgets.QLabel(self.orbitsGroupBox)
        self.label.setGeometry(QtCore.QRect(20, 51, 16, 16))
        self.label.setObjectName("label")
        self.lineEdit_p = QtWidgets.QLineEdit(self.orbitsGroupBox)
        self.lineEdit_p.setEnabled(True)
        self.lineEdit_p.setGeometry(QtCore.QRect(40, 81, 141, 19))
        self.lineEdit_p.setText("")
        self.lineEdit_p.setObjectName("lineEdit_p")
        self.lineEdit_q = QtWidgets.QLineEdit(self.orbitsGroupBox)
        self.lineEdit_q.setEnabled(True)
        self.lineEdit_q.setGeometry(QtCore.QRect(40, 51, 141, 20))
        self.lineEdit_q.setText("")
        self.lineEdit_q.setObjectName("lineEdit_q")
        self.label_9 = QtWidgets.QLabel(self.orbitsGroupBox)
        self.label_9.setGeometry(QtCore.QRect(20, 81, 16, 16))
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(self.orbitsGroupBox)
        self.label_4.setGeometry(QtCore.QRect(210, 80, 58, 16))
        self.label_4.setObjectName("label_4")
        self.samplenum_lineEdit = QtWidgets.QLineEdit(self.orbitsGroupBox)
        self.samplenum_lineEdit.setGeometry(QtCore.QRect(280, 50, 51, 20))
        self.samplenum_lineEdit.setInputMask("")
        self.samplenum_lineEdit.setObjectName("samplenum_lineEdit")
        self.label_2 = QtWidgets.QLabel(self.orbitsGroupBox)
        self.label_2.setGeometry(QtCore.QRect(190, 50, 82, 16))
        self.label_2.setObjectName("label_2")
        self.label_11 = QtWidgets.QLabel(self.orbitsGroupBox)
        self.label_11.setGeometry(QtCore.QRect(265, 170, 19, 16))
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(self.orbitsGroupBox)
        self.label_10.setGeometry(QtCore.QRect(180, 170, 39, 16))
        self.label_10.setObjectName("label_10")
        self.lineEdit_SI_dt = QtWidgets.QLineEdit(self.orbitsGroupBox)
        self.lineEdit_SI_dt.setGeometry(QtCore.QRect(292, 170, 58, 21))
        self.lineEdit_SI_dt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_SI_dt.setObjectName("lineEdit_SI_dt")
        self.lineEdit_SI_order = QtWidgets.QLineEdit(self.orbitsGroupBox)
        self.lineEdit_SI_order.setGeometry(QtCore.QRect(224, 170, 31, 21))
        self.lineEdit_SI_order.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_SI_order.setObjectName("lineEdit_SI_order")
        self.label_14 = QtWidgets.QLabel(self.orbitsGroupBox)
        self.label_14.setGeometry(QtCore.QRect(50, 110, 41, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit = QtWidgets.QLineEdit(self.orbitsGroupBox)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(90, 110, 51, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.spinBoxIteration = QtWidgets.QSpinBox(self.orbitsGroupBox)
        self.spinBoxIteration.setEnabled(False)
        self.spinBoxIteration.setGeometry(QtCore.QRect(330, 80, 20, 24))
        self.spinBoxIteration.setMaximum(10000)
        self.spinBoxIteration.setProperty("value", 1000)
        self.spinBoxIteration.setObjectName("spinBoxIteration")
        self.label.raise_()
        self.lineEdit_p.raise_()
        self.lineEdit_q.raise_()
        self.label_9.raise_()
        self.label_4.raise_()
        self.samplenum_lineEdit.raise_()
        self.label_2.raise_()
        self.label_11.raise_()
        self.label_10.raise_()
        self.lineEdit_SI_dt.raise_()
        self.lineEdit_SI_order.raise_()
        self.plotButton.raise_()
        self.comboBox_Select_Init.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.itaration_lineEdit.raise_()
        self.label_14.raise_()
        self.lineEdit.raise_()
        self.spinBoxIteration.raise_()
        self.canvasBox = QtWidgets.QGroupBox(self.centralwidget)
        self.canvasBox.setGeometry(QtCore.QRect(10, 0, 591, 661))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvasBox.sizePolicy().hasHeightForWidth())
        self.canvasBox.setSizePolicy(sizePolicy)
        self.canvasBox.setTitle("")
        self.canvasBox.setObjectName("canvasBox")
        self.ReplotButton = QtWidgets.QPushButton(self.canvasBox)
        self.ReplotButton.setGeometry(QtCore.QRect(480, 630, 114, 32))
        self.ReplotButton.setObjectName("ReplotButton")
        self.canvasClearButton = QtWidgets.QPushButton(self.canvasBox)
        self.canvasClearButton.setGeometry(QtCore.QRect(370, 630, 114, 32))
        self.canvasClearButton.setObjectName("canvasClearButton")
        self.lineEdit_qrange = QtWidgets.QLineEdit(self.canvasBox)
        self.lineEdit_qrange.setGeometry(QtCore.QRect(422, 605, 68, 21))
        self.lineEdit_qrange.setObjectName("lineEdit_qrange")
        self.label_3 = QtWidgets.QLabel(self.canvasBox)
        self.label_3.setGeometry(QtCore.QRect(401, 605, 16, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_prange = QtWidgets.QLineEdit(self.canvasBox)
        self.lineEdit_prange.setGeometry(QtCore.QRect(521, 605, 69, 21))
        self.lineEdit_prange.setObjectName("lineEdit_prange")
        self.label_12 = QtWidgets.QLabel(self.canvasBox)
        self.label_12.setGeometry(QtCore.QRect(500, 605, 16, 16))
        self.label_12.setObjectName("label_12")
        self.checkBoxClickable = QtWidgets.QCheckBox(self.canvasBox)
        self.checkBoxClickable.setGeometry(QtCore.QRect(514, 584, 87, 20))
        self.checkBoxClickable.setChecked(True)
        self.checkBoxClickable.setObjectName("checkBoxClickable")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(630, 250, 351, 381))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.ParameterButton = QtWidgets.QPushButton(self.groupBox_2)
        self.ParameterButton.setGeometry(QtCore.QRect(230, 320, 114, 32))
        self.ParameterButton.setObjectName("ParameterButton")
        self.label_SystemInfo = QtWidgets.QLabel(self.groupBox_2)
        self.label_SystemInfo.setGeometry(QtCore.QRect(20, 50, 311, 41))
        self.label_SystemInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_SystemInfo.setObjectName("label_SystemInfo")
        self.label_Periodicity = QtWidgets.QLabel(self.groupBox_2)
        self.label_Periodicity.setGeometry(QtCore.QRect(20, 280, 311, 41))
        self.label_Periodicity.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_Periodicity.setObjectName("label_Periodicity")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 251, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 260, 181, 16))
        self.label_6.setObjectName("label_6")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(20, 150, 81, 16))
        self.label_13.setObjectName("label_13")
        self.label_Parameters = QtWidgets.QLabel(self.groupBox_2)
        self.label_Parameters.setGeometry(QtCore.QRect(20, 170, 311, 61))
        self.label_Parameters.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_Parameters.setObjectName("label_Parameters")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1005, 17))
        self.menubar.setObjectName("menubar")
        self.menuQtMapy = QtWidgets.QMenu(self.menubar)
        self.menuQtMapy.setObjectName("menuQtMapy")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuMapping = QtWidgets.QMenu(self.menubar)
        self.menuMapping.setObjectName("menuMapping")
        self.menuAnalysis = QtWidgets.QMenu(self.menubar)
        self.menuAnalysis.setObjectName("menuAnalysis")
        self.menuClassical = QtWidgets.QMenu(self.menuAnalysis)
        self.menuClassical.setObjectName("menuClassical")
        self.menuQuantum = QtWidgets.QMenu(self.menuAnalysis)
        self.menuQuantum.setEnabled(True)
        self.menuQuantum.setObjectName("menuQuantum")
        self.menuComplex = QtWidgets.QMenu(self.menuAnalysis)
        self.menuComplex.setEnabled(True)
        self.menuComplex.setObjectName("menuComplex")
        self.menuSemiclassical = QtWidgets.QMenu(self.menuAnalysis)
        self.menuSemiclassical.setEnabled(False)
        self.menuSemiclassical.setObjectName("menuSemiclassical")
        self.menuShow = QtWidgets.QMenu(self.menubar)
        self.menuShow.setObjectName("menuShow")
        MainWindow.setMenuBar(self.menubar)
        self.actionAboutQtMapy = QtWidgets.QAction(MainWindow)
        self.actionAboutQtMapy.setObjectName("actionAboutQtMapy")
        self.actionAboutMapy = QtWidgets.QAction(MainWindow)
        self.actionAboutMapy.setEnabled(False)
        self.actionAboutMapy.setObjectName("actionAboutMapy")
        self.actionOpen_new_window = QtWidgets.QAction(MainWindow)
        self.actionOpen_new_window.setEnabled(False)
        self.actionOpen_new_window.setObjectName("actionOpen_new_window")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setEnabled(False)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setEnabled(False)
        self.actionLoad.setObjectName("actionLoad")
        self.actionHenon_map = QtWidgets.QAction(MainWindow)
        self.actionHenon_map.setCheckable(True)
        self.actionHenon_map.setObjectName("actionHenon_map")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionTest = QtWidgets.QAction(MainWindow)
        self.actionTest.setObjectName("actionTest")
        self.actionHarper_map = QtWidgets.QAction(MainWindow)
        self.actionHarper_map.setCheckable(True)
        self.actionHarper_map.setObjectName("actionHarper_map")
        self.actionStandard_map = QtWidgets.QAction(MainWindow)
        self.actionStandard_map.setCheckable(True)
        self.actionStandard_map.setChecked(True)
        self.actionStandard_map.setObjectName("actionStandard_map")
        self.actionHarmonic_map = QtWidgets.QAction(MainWindow)
        self.actionHarmonic_map.setCheckable(True)
        self.actionHarmonic_map.setObjectName("actionHarmonic_map")
        self.actionTimeEvolve = QtWidgets.QAction(MainWindow)
        self.actionTimeEvolve.setCheckable(True)
        self.actionTimeEvolve.setEnabled(False)
        self.actionTimeEvolve.setObjectName("actionTimeEvolve")
        self.actionMapping = QtWidgets.QAction(MainWindow)
        self.actionMapping.setCheckable(True)
        self.actionMapping.setChecked(True)
        self.actionMapping.setObjectName("actionMapping")
        self.actionStable_Unstable_mfd = QtWidgets.QAction(MainWindow)
        self.actionStable_Unstable_mfd.setCheckable(True)
        self.actionStable_Unstable_mfd.setEnabled(False)
        self.actionStable_Unstable_mfd.setObjectName("actionStable_Unstable_mfd")
        self.actionTimeDomain = QtWidgets.QAction(MainWindow)
        self.actionTimeDomain.setEnabled(False)
        self.actionTimeDomain.setObjectName("actionTimeDomain")
        self.actionEnergyDomain = QtWidgets.QAction(MainWindow)
        self.actionEnergyDomain.setObjectName("actionEnergyDomain")
        self.actionComplex_KAM = QtWidgets.QAction(MainWindow)
        self.actionComplex_KAM.setEnabled(False)
        self.actionComplex_KAM.setObjectName("actionComplex_KAM")
        self.actionKAM_curve = QtWidgets.QAction(MainWindow)
        self.actionKAM_curve.setCheckable(True)
        self.actionKAM_curve.setEnabled(False)
        self.actionKAM_curve.setObjectName("actionKAM_curve")
        self.actionFrequency_Map_Anaysis = QtWidgets.QAction(MainWindow)
        self.actionFrequency_Map_Anaysis.setCheckable(True)
        self.actionFrequency_Map_Anaysis.setEnabled(False)
        self.actionFrequency_Map_Anaysis.setObjectName("actionFrequency_Map_Anaysis")
        self.actionM_set = QtWidgets.QAction(MainWindow)
        self.actionM_set.setObjectName("actionM_set")
        self.actionL_set = QtWidgets.QAction(MainWindow)
        self.actionL_set.setObjectName("actionL_set")
        self.actionEnergy_contour = QtWidgets.QAction(MainWindow)
        self.actionEnergy_contour.setObjectName("actionEnergy_contour")
        self.actionMset = QtWidgets.QAction(MainWindow)
        self.actionMset.setObjectName("actionMset")
        self.menuQtMapy.addAction(self.actionAboutQtMapy)
        self.menuQtMapy.addAction(self.actionAboutMapy)
        self.menuQtMapy.addSeparator()
        self.menuQtMapy.addAction(self.actionQuit)
        self.menuFile.addAction(self.actionOpen_new_window)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addSeparator()
        self.menuClassical.addAction(self.actionMapping)
        self.menuClassical.addAction(self.actionTimeEvolve)
        self.menuClassical.addAction(self.actionStable_Unstable_mfd)
        self.menuClassical.addAction(self.actionKAM_curve)
        self.menuClassical.addAction(self.actionFrequency_Map_Anaysis)
        self.menuQuantum.addAction(self.actionEnergyDomain)
        self.menuQuantum.addAction(self.actionTimeDomain)
        self.menuComplex.addAction(self.actionComplex_KAM)
        self.menuComplex.addAction(self.actionMset)
        self.menuSemiclassical.addAction(self.actionM_set)
        self.menuSemiclassical.addAction(self.actionL_set)
        self.menuAnalysis.addAction(self.menuClassical.menuAction())
        self.menuAnalysis.addAction(self.menuQuantum.menuAction())
        self.menuAnalysis.addAction(self.menuComplex.menuAction())
        self.menuAnalysis.addAction(self.menuSemiclassical.menuAction())
        self.menuShow.addAction(self.actionEnergy_contour)
        self.menubar.addAction(self.menuQtMapy.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMapping.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
        self.menubar.addAction(self.menuShow.menuAction())

        self.retranslateUi(MainWindow)
        self.closeButton.clicked.connect(MainWindow.close)
        self.actionQuit.triggered.connect(MainWindow.close)
        self.lineEdit_qrange.returnPressed.connect(self.ReplotButton.animateClick)
        self.lineEdit_prange.returnPressed.connect(self.ReplotButton.animateClick)
        self.lineEdit_q.returnPressed.connect(self.plotButton.animateClick)
        self.lineEdit_p.returnPressed.connect(self.plotButton.animateClick)
        self.samplenum_lineEdit.returnPressed.connect(self.plotButton.animateClick)
        self.itaration_lineEdit.returnPressed.connect(self.plotButton.animateClick)
        self.lineEdit.returnPressed.connect(self.plotButton.animateClick)
        self.spinBoxIteration.editingFinished.connect(self.plotButton.animateClick)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_q, self.lineEdit_p)
        MainWindow.setTabOrder(self.lineEdit_p, self.samplenum_lineEdit)
        MainWindow.setTabOrder(self.samplenum_lineEdit, self.itaration_lineEdit)
        MainWindow.setTabOrder(self.itaration_lineEdit, self.lineEdit_SI_order)
        MainWindow.setTabOrder(self.lineEdit_SI_order, self.lineEdit_SI_dt)
        MainWindow.setTabOrder(self.lineEdit_SI_dt, self.plotButton)
        MainWindow.setTabOrder(self.plotButton, self.comboBox_Select_Init)
        MainWindow.setTabOrder(self.comboBox_Select_Init, self.lineEdit_qrange)
        MainWindow.setTabOrder(self.lineEdit_qrange, self.lineEdit_prange)
        MainWindow.setTabOrder(self.lineEdit_prange, self.canvasClearButton)
        MainWindow.setTabOrder(self.canvasClearButton, self.ReplotButton)
        MainWindow.setTabOrder(self.ReplotButton, self.ParameterButton)
        MainWindow.setTabOrder(self.ParameterButton, self.closeButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QtMapy"))
        self.closeButton.setText(_translate("MainWindow", "Close"))
        self.orbitsGroupBox.setTitle(_translate("MainWindow", "iteration configuratoin"))
        self.plotButton.setText(_translate("MainWindow", "Plot"))
        self.comboBox_Select_Init.setItemText(0, _translate("MainWindow", "point"))
        self.comboBox_Select_Init.setItemText(1, _translate("MainWindow", "random"))
        self.comboBox_Select_Init.setItemText(2, _translate("MainWindow", "linear"))
        self.comboBox_Select_Init.setItemText(3, _translate("MainWindow", "box"))
        self.comboBox_Select_Init.setItemText(4, _translate("MainWindow", "circle"))
        self.label_7.setText(_translate("MainWindow", "initial condition:"))
        self.label_8.setText(_translate("MainWindow", "Symplectic Integrator condition"))
        self.itaration_lineEdit.setText(_translate("MainWindow", "1000"))
        self.label.setText(_translate("MainWindow", "q:"))
        self.label_9.setText(_translate("MainWindow", "p:"))
        self.label_4.setText(_translate("MainWindow", "itaration:"))
        self.samplenum_lineEdit.setText(_translate("MainWindow", "100"))
        self.label_2.setText(_translate("MainWindow", "sample num:"))
        self.label_11.setText(_translate("MainWindow", "Δt:"))
        self.label_10.setText(_translate("MainWindow", "order:"))
        self.lineEdit_SI_dt.setText(_translate("MainWindow", "1"))
        self.lineEdit_SI_order.setText(_translate("MainWindow", "1"))
        self.label_14.setText(_translate("MainWindow", "radius"))
        self.ReplotButton.setText(_translate("MainWindow", "Set Range"))
        self.canvasClearButton.setText(_translate("MainWindow", "Canvas Clear"))
        self.lineEdit_qrange.setText(_translate("MainWindow", "-pi, pi"))
        self.label_3.setText(_translate("MainWindow", "q:"))
        self.lineEdit_prange.setText(_translate("MainWindow", "-pi,pi"))
        self.label_12.setText(_translate("MainWindow", "p:"))
        self.checkBoxClickable.setText(_translate("MainWindow", "clickable"))
        self.groupBox_2.setTitle(_translate("MainWindow", "map system configuration"))
        self.ParameterButton.setText(_translate("MainWindow", "Parameters"))
        self.label_SystemInfo.setText(_translate("MainWindow", "difinition"))
        self.label_Periodicity.setText(_translate("MainWindow", "Periodicity Condition"))
        self.label_5.setText(_translate("MainWindow", "Hamiltonian: H(q,p) = T(q,p) + V(q,p)"))
        self.label_6.setText(_translate("MainWindow", "Periodic boundary condition:"))
        self.label_13.setText(_translate("MainWindow", "Parameters:"))
        self.label_Parameters.setText(_translate("MainWindow", "Some Parameters"))
        self.menuQtMapy.setTitle(_translate("MainWindow", "QtMapy"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuMapping.setTitle(_translate("MainWindow", "Mapping"))
        self.menuAnalysis.setTitle(_translate("MainWindow", "Analysis"))
        self.menuClassical.setTitle(_translate("MainWindow", "Classical"))
        self.menuQuantum.setTitle(_translate("MainWindow", "Quantum"))
        self.menuComplex.setTitle(_translate("MainWindow", "Complex"))
        self.menuSemiclassical.setTitle(_translate("MainWindow", "Semiclassical"))
        self.menuShow.setTitle(_translate("MainWindow", "Show"))
        self.actionAboutQtMapy.setText(_translate("MainWindow", "QtMapyについて"))
        self.actionAboutMapy.setText(_translate("MainWindow", "mapyについて"))
        self.actionOpen_new_window.setText(_translate("MainWindow", "open new window"))
        self.actionSave.setText(_translate("MainWindow", "save"))
        self.actionLoad.setText(_translate("MainWindow", "load"))
        self.actionHenon_map.setText(_translate("MainWindow", "Henon map"))
        self.actionQuit.setText(_translate("MainWindow", "Close"))
        self.actionTest.setText(_translate("MainWindow", "test"))
        self.actionHarper_map.setText(_translate("MainWindow", "Harper map"))
        self.actionStandard_map.setText(_translate("MainWindow", "Standard map"))
        self.actionHarmonic_map.setText(_translate("MainWindow", "Harmonic map"))
        self.actionTimeEvolve.setText(_translate("MainWindow", "Time evolution"))
        self.actionMapping.setText(_translate("MainWindow", "Mapping"))
        self.actionStable_Unstable_mfd.setText(_translate("MainWindow", "Stable/Unstable mfd"))
        self.actionTimeDomain.setText(_translate("MainWindow", "Time domain"))
        self.actionEnergyDomain.setText(_translate("MainWindow", "Energy domain"))
        self.actionComplex_KAM.setText(_translate("MainWindow", "Complex KAM"))
        self.actionKAM_curve.setText(_translate("MainWindow", "KAM curve"))
        self.actionFrequency_Map_Anaysis.setText(_translate("MainWindow", "Frequency Map Anaysis"))
        self.actionM_set.setText(_translate("MainWindow", "M set"))
        self.actionL_set.setText(_translate("MainWindow", "L set"))
        self.actionEnergy_contour.setText(_translate("MainWindow", "Energy contour"))
        self.actionMset.setText(_translate("MainWindow", "Mset"))

