# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maindesign.ui'
#
# Created: Sat Jul 12 12:57:55 2014
#      by: PySide UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1000, 700)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.closeButton = QtGui.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(880, 630, 114, 32))
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(600, 0, 20, 661))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.orbitsGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.orbitsGroupBox.setGeometry(QtCore.QRect(630, 0, 351, 191))
        self.orbitsGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.orbitsGroupBox.setObjectName(_fromUtf8("orbitsGroupBox"))
        self.plotButton = QtGui.QPushButton(self.orbitsGroupBox)
        self.plotButton.setGeometry(QtCore.QRect(240, 110, 114, 32))
        self.plotButton.setObjectName(_fromUtf8("plotButton"))
        self.comboBox = QtGui.QComboBox(self.orbitsGroupBox)
        self.comboBox.setEnabled(True)
        self.comboBox.setGeometry(QtCore.QRect(121, 20, 111, 26))
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setMinimumContentsLength(0)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.label_7 = QtGui.QLabel(self.orbitsGroupBox)
        self.label_7.setGeometry(QtCore.QRect(14, 23, 111, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.orbitsGroupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 130, 211, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.itaration_lineEdit = QtGui.QLineEdit(self.orbitsGroupBox)
        self.itaration_lineEdit.setGeometry(QtCore.QRect(261, 81, 89, 19))
        self.itaration_lineEdit.setObjectName(_fromUtf8("itaration_lineEdit"))
        self.label = QtGui.QLabel(self.orbitsGroupBox)
        self.label.setGeometry(QtCore.QRect(51, 51, 16, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEdit_2 = QtGui.QLineEdit(self.orbitsGroupBox)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QtCore.QRect(72, 81, 89, 19))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit = QtGui.QLineEdit(self.orbitsGroupBox)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(72, 51, 89, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_9 = QtGui.QLabel(self.orbitsGroupBox)
        self.label_9.setGeometry(QtCore.QRect(51, 81, 16, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_4 = QtGui.QLabel(self.orbitsGroupBox)
        self.label_4.setGeometry(QtCore.QRect(171, 81, 58, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.samplenum_lineEdit = QtGui.QLineEdit(self.orbitsGroupBox)
        self.samplenum_lineEdit.setGeometry(QtCore.QRect(261, 51, 89, 20))
        self.samplenum_lineEdit.setInputMask(_fromUtf8(""))
        self.samplenum_lineEdit.setObjectName(_fromUtf8("samplenum_lineEdit"))
        self.label_2 = QtGui.QLabel(self.orbitsGroupBox)
        self.label_2.setGeometry(QtCore.QRect(171, 51, 82, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_11 = QtGui.QLabel(self.orbitsGroupBox)
        self.label_11.setGeometry(QtCore.QRect(265, 165, 19, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_10 = QtGui.QLabel(self.orbitsGroupBox)
        self.label_10.setGeometry(QtCore.QRect(151, 165, 39, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_SI_dt = QtGui.QLineEdit(self.orbitsGroupBox)
        self.lineEdit_SI_dt.setGeometry(QtCore.QRect(292, 165, 58, 21))
        self.lineEdit_SI_dt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_SI_dt.setObjectName(_fromUtf8("lineEdit_SI_dt"))
        self.lineEdit_SI_order = QtGui.QLineEdit(self.orbitsGroupBox)
        self.lineEdit_SI_order.setGeometry(QtCore.QRect(198, 165, 57, 21))
        self.lineEdit_SI_order.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_SI_order.setObjectName(_fromUtf8("lineEdit_SI_order"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 591, 661))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.ReplotButton = QtGui.QPushButton(self.groupBox)
        self.ReplotButton.setGeometry(QtCore.QRect(480, 630, 114, 32))
        self.ReplotButton.setObjectName(_fromUtf8("ReplotButton"))
        self.canvasClearButton = QtGui.QPushButton(self.groupBox)
        self.canvasClearButton.setGeometry(QtCore.QRect(370, 630, 114, 32))
        self.canvasClearButton.setObjectName(_fromUtf8("canvasClearButton"))
        self.mpl = MplWidget(self.groupBox)
        self.mpl.setGeometry(QtCore.QRect(10, 20, 571, 561))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        self.mpl.setObjectName(_fromUtf8("mpl"))
        self.lineEdit_qrange = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_qrange.setGeometry(QtCore.QRect(422, 605, 68, 21))
        self.lineEdit_qrange.setObjectName(_fromUtf8("lineEdit_qrange"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(401, 605, 16, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit_prange = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_prange.setGeometry(QtCore.QRect(521, 605, 69, 21))
        self.lineEdit_prange.setObjectName(_fromUtf8("lineEdit_prange"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(500, 605, 16, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(630, 220, 351, 411))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.ParameterButton = QtGui.QPushButton(self.groupBox_2)
        self.ParameterButton.setGeometry(QtCore.QRect(230, 370, 114, 32))
        self.ParameterButton.setObjectName(_fromUtf8("ParameterButton"))
        self.label_SystemInfo = QtGui.QLabel(self.groupBox_2)
        self.label_SystemInfo.setGeometry(QtCore.QRect(20, 50, 311, 41))
        self.label_SystemInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_SystemInfo.setObjectName(_fromUtf8("label_SystemInfo"))
        self.label_Periodicity = QtGui.QLabel(self.groupBox_2)
        self.label_Periodicity.setGeometry(QtCore.QRect(20, 290, 311, 41))
        self.label_Periodicity.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_Periodicity.setObjectName(_fromUtf8("label_Periodicity"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 251, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 270, 181, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(20, 150, 81, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_Parameters = QtGui.QLabel(self.groupBox_2)
        self.label_Parameters.setGeometry(QtCore.QRect(20, 170, 311, 61))
        self.label_Parameters.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_Parameters.setObjectName(_fromUtf8("label_Parameters"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar() #QtGui.QStatusBar(MainWindow) 
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuQtMapy = QtGui.QMenu(self.menubar)
        self.menuQtMapy.setObjectName(_fromUtf8("menuQtMapy"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuMapping = QtGui.QMenu(self.menubar)
        self.menuMapping.setObjectName(_fromUtf8("menuMapping"))
        self.menuAnalysis = QtGui.QMenu(self.menubar)
        self.menuAnalysis.setObjectName(_fromUtf8("menuAnalysis"))
        self.menuClassical = QtGui.QMenu(self.menuAnalysis)
        self.menuClassical.setObjectName(_fromUtf8("menuClassical"))
        self.menuQuantum = QtGui.QMenu(self.menuAnalysis)
        self.menuQuantum.setEnabled(False)
        self.menuQuantum.setObjectName(_fromUtf8("menuQuantum"))
        self.menuComplex = QtGui.QMenu(self.menuAnalysis)
        self.menuComplex.setEnabled(False)
        self.menuComplex.setObjectName(_fromUtf8("menuComplex"))
        self.menuSemiclassical = QtGui.QMenu(self.menuAnalysis)
        self.menuSemiclassical.setEnabled(False)
        self.menuSemiclassical.setObjectName(_fromUtf8("menuSemiclassical"))
        MainWindow.setMenuBar(self.menubar)
        self.actionAboutQtMapy = QtGui.QAction(MainWindow)
        self.actionAboutQtMapy.setObjectName(_fromUtf8("actionAboutQtMapy"))
        self.actionAboutMapy = QtGui.QAction(MainWindow)
        self.actionAboutMapy.setEnabled(False)
        self.actionAboutMapy.setObjectName(_fromUtf8("actionAboutMapy"))
        self.actionOpen_new_window = QtGui.QAction(MainWindow)
        self.actionOpen_new_window.setEnabled(False)
        self.actionOpen_new_window.setObjectName(_fromUtf8("actionOpen_new_window"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setEnabled(False)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setEnabled(False)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionHenon_map = QtGui.QAction(MainWindow)
        self.actionHenon_map.setCheckable(True)
        self.actionHenon_map.setObjectName(_fromUtf8("actionHenon_map"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionTest = QtGui.QAction(MainWindow)
        self.actionTest.setObjectName(_fromUtf8("actionTest"))
        self.actionHarper_map = QtGui.QAction(MainWindow)
        self.actionHarper_map.setCheckable(True)
        self.actionHarper_map.setObjectName(_fromUtf8("actionHarper_map"))
        self.actionStandard_map = QtGui.QAction(MainWindow)
        self.actionStandard_map.setCheckable(True)
        self.actionStandard_map.setChecked(True)
        self.actionStandard_map.setObjectName(_fromUtf8("actionStandard_map"))
        self.actionHarmonic_map = QtGui.QAction(MainWindow)
        self.actionHarmonic_map.setCheckable(True)
        self.actionHarmonic_map.setObjectName(_fromUtf8("actionHarmonic_map"))
        self.actionTimeEvolve = QtGui.QAction(MainWindow)
        self.actionTimeEvolve.setCheckable(True)
        self.actionTimeEvolve.setEnabled(False)
        self.actionTimeEvolve.setObjectName(_fromUtf8("actionTimeEvolve"))
        self.actionMapping = QtGui.QAction(MainWindow)
        self.actionMapping.setCheckable(True)
        self.actionMapping.setChecked(True)
        self.actionMapping.setObjectName(_fromUtf8("actionMapping"))
        self.actionStable_Unstable_mfd = QtGui.QAction(MainWindow)
        self.actionStable_Unstable_mfd.setCheckable(True)
        self.actionStable_Unstable_mfd.setEnabled(False)
        self.actionStable_Unstable_mfd.setObjectName(_fromUtf8("actionStable_Unstable_mfd"))
        self.actionTime_Evolution = QtGui.QAction(MainWindow)
        self.actionTime_Evolution.setObjectName(_fromUtf8("actionTime_Evolution"))
        self.actionEnergy_domain = QtGui.QAction(MainWindow)
        self.actionEnergy_domain.setObjectName(_fromUtf8("actionEnergy_domain"))
        self.actionComplex_KAM = QtGui.QAction(MainWindow)
        self.actionComplex_KAM.setObjectName(_fromUtf8("actionComplex_KAM"))
        self.actionKAM_curve = QtGui.QAction(MainWindow)
        self.actionKAM_curve.setCheckable(True)
        self.actionKAM_curve.setEnabled(False)
        self.actionKAM_curve.setObjectName(_fromUtf8("actionKAM_curve"))
        self.actionFrequency_Map_Anaysis = QtGui.QAction(MainWindow)
        self.actionFrequency_Map_Anaysis.setCheckable(True)
        self.actionFrequency_Map_Anaysis.setEnabled(False)
        self.actionFrequency_Map_Anaysis.setObjectName(_fromUtf8("actionFrequency_Map_Anaysis"))
        self.actionM_set = QtGui.QAction(MainWindow)
        self.actionM_set.setObjectName(_fromUtf8("actionM_set"))
        self.actionL_set = QtGui.QAction(MainWindow)
        self.actionL_set.setObjectName(_fromUtf8("actionL_set"))
        self.menuQtMapy.addAction(self.actionAboutQtMapy)
        self.menuQtMapy.addAction(self.actionAboutMapy)
        self.menuQtMapy.addSeparator()
        self.menuQtMapy.addAction(self.actionQuit)
        self.menuFile.addAction(self.actionOpen_new_window)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addSeparator()
        self.menuMapping.addAction(self.actionStandard_map)
        self.menuMapping.addAction(self.actionHenon_map)
        self.menuMapping.addAction(self.actionHarper_map)
        self.menuMapping.addAction(self.actionHarmonic_map)
        self.menuClassical.addAction(self.actionMapping)
        self.menuClassical.addAction(self.actionTimeEvolve)
        self.menuClassical.addAction(self.actionStable_Unstable_mfd)
        self.menuClassical.addAction(self.actionKAM_curve)
        self.menuClassical.addAction(self.actionFrequency_Map_Anaysis)
        self.menuQuantum.addAction(self.actionTime_Evolution)
        self.menuQuantum.addAction(self.actionEnergy_domain)
        self.menuComplex.addAction(self.actionComplex_KAM)
        self.menuSemiclassical.addAction(self.actionM_set)
        self.menuSemiclassical.addAction(self.actionL_set)
        self.menuAnalysis.addAction(self.menuClassical.menuAction())
        self.menuAnalysis.addAction(self.menuQuantum.menuAction())
        self.menuAnalysis.addAction(self.menuComplex.menuAction())
        self.menuAnalysis.addAction(self.menuSemiclassical.menuAction())
        self.menubar.addAction(self.menuQtMapy.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMapping.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.closeButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.lineEdit_qrange, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.ReplotButton.animateClick)
        QtCore.QObject.connect(self.lineEdit_prange, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.ReplotButton.animateClick)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.samplenum_lineEdit)
        MainWindow.setTabOrder(self.samplenum_lineEdit, self.itaration_lineEdit)
        MainWindow.setTabOrder(self.itaration_lineEdit, self.lineEdit_SI_order)
        MainWindow.setTabOrder(self.lineEdit_SI_order, self.lineEdit_SI_dt)
        MainWindow.setTabOrder(self.lineEdit_SI_dt, self.plotButton)
        MainWindow.setTabOrder(self.plotButton, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.lineEdit_qrange)
        MainWindow.setTabOrder(self.lineEdit_qrange, self.lineEdit_prange)
        MainWindow.setTabOrder(self.lineEdit_prange, self.canvasClearButton)
        MainWindow.setTabOrder(self.canvasClearButton, self.ReplotButton)
        MainWindow.setTabOrder(self.ReplotButton, self.ParameterButton)
        MainWindow.setTabOrder(self.ParameterButton, self.closeButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.closeButton.setText(_translate("MainWindow", "Close", None))
        self.orbitsGroupBox.setTitle(_translate("MainWindow", "iteration configuratoin", None))
        self.plotButton.setText(_translate("MainWindow", "Plot", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "point", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "random", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "linear", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "box", None))
        self.comboBox.setItemText(4, _translate("MainWindow", "circle", None))
        self.label_7.setText(_translate("MainWindow", "initial condition:", None))
        self.label_8.setText(_translate("MainWindow", "Symplectic Integrator condition", None))
        self.itaration_lineEdit.setText(_translate("MainWindow", "1000", None))
        self.label.setText(_translate("MainWindow", "q:", None))
        self.label_9.setText(_translate("MainWindow", "p:", None))
        self.label_4.setText(_translate("MainWindow", "itaration:", None))
        self.samplenum_lineEdit.setText(_translate("MainWindow", "100", None))
        self.label_2.setText(_translate("MainWindow", "sample num:", None))
        self.label_11.setText(_translate("MainWindow", "Δt:", None))
        self.label_10.setText(_translate("MainWindow", "order:", None))
        self.lineEdit_SI_dt.setText(_translate("MainWindow", "1", None))
        self.lineEdit_SI_order.setText(_translate("MainWindow", "1", None))
        self.ReplotButton.setText(_translate("MainWindow", "Replot", None))
        self.canvasClearButton.setText(_translate("MainWindow", "Canvas Clear", None))
        self.lineEdit_qrange.setText(_translate("MainWindow", "-pi, pi", None))
        self.label_3.setText(_translate("MainWindow", "q:", None))
        self.lineEdit_prange.setText(_translate("MainWindow", "-pi,pi", None))
        self.label_12.setText(_translate("MainWindow", "p:", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "map system configuration", None))
        self.ParameterButton.setText(_translate("MainWindow", "Parameters", None))
        self.label_SystemInfo.setText(_translate("MainWindow", "difinition", None))
        self.label_Periodicity.setText(_translate("MainWindow", "Periodicity Condition", None))
        self.label_5.setText(_translate("MainWindow", "Hamiltonian: H(q,p) = T(q,p) + V(q,p)", None))
        self.label_6.setText(_translate("MainWindow", "Periodic boundary condition:", None))
        self.label_13.setText(_translate("MainWindow", "Parameters:", None))
        self.label_Parameters.setText(_translate("MainWindow", "Some Parameters", None))
        self.menuQtMapy.setTitle(_translate("MainWindow", "QtMapy", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuMapping.setTitle(_translate("MainWindow", "Mapping", None))
        self.menuAnalysis.setTitle(_translate("MainWindow", "Analysis", None))
        self.menuClassical.setTitle(_translate("MainWindow", "Classical", None))
        self.menuQuantum.setTitle(_translate("MainWindow", "Quantum", None))
        self.menuComplex.setTitle(_translate("MainWindow", "Complex", None))
        self.menuSemiclassical.setTitle(_translate("MainWindow", "Semiclassical", None))
        self.actionAboutQtMapy.setText(_translate("MainWindow", "QtMapyについて", None))
        self.actionAboutMapy.setText(_translate("MainWindow", "mapyについて", None))
        self.actionOpen_new_window.setText(_translate("MainWindow", "open new window", None))
        self.actionSave.setText(_translate("MainWindow", "save", None))
        self.actionLoad.setText(_translate("MainWindow", "load", None))
        self.actionHenon_map.setText(_translate("MainWindow", "Henon map", None))
        self.actionQuit.setText(_translate("MainWindow", "QtMapを終了", None))
        self.actionTest.setText(_translate("MainWindow", "test", None))
        self.actionHarper_map.setText(_translate("MainWindow", "Harper map", None))
        self.actionStandard_map.setText(_translate("MainWindow", "Standard map", None))
        self.actionHarmonic_map.setText(_translate("MainWindow", "Harmonic map", None))
        self.actionTimeEvolve.setText(_translate("MainWindow", "Time evolution", None))
        self.actionMapping.setText(_translate("MainWindow", "Mapping", None))
        self.actionStable_Unstable_mfd.setText(_translate("MainWindow", "Stable/Unstable mfd", None))
        self.actionTime_Evolution.setText(_translate("MainWindow", "Time domain", None))
        self.actionEnergy_domain.setText(_translate("MainWindow", "Energy domain", None))
        self.actionComplex_KAM.setText(_translate("MainWindow", "Complex KAM", None))
        self.actionKAM_curve.setText(_translate("MainWindow", "KAM curve", None))
        self.actionFrequency_Map_Anaysis.setText(_translate("MainWindow", "Frequency Map Anaysis", None))
        self.actionM_set.setText(_translate("MainWindow", "M set", None))
        self.actionL_set.setText(_translate("MainWindow", "L set", None))

from .mplwidget import MplWidget
