
from __future__ import with_statement
from PyQt4 import QtCore, QtGui

import numpy as np
import sympy
import sys
import mapy
from mapy.QtMapy.Mapping import Mapping
import inspect

twopi = 2*np.pi

# import the MainWindow widget from the converted .ui files
from .Design.maindesign import Ui_MainWindow
from .Design.popupAbout import Ui_AboutDialog

#MapSystemNames=['Henon', '']


class AboutDialog(QtGui.QDialog, Ui_AboutDialog):
    def __init__(self,parent=None):
        QtGui.QDialog.__init__(self,parent)
        self.setupUi(self)

class ParameterDialog(QtGui.QDialog):
    def __init__(self, mapsys, parent=None):
        QtGui.QDialog.__init__(self,parent)

        grid = QtGui.QGridLayout()
        args = inspect.getargspec(mapsys.__init__)[0][1:]
        parameters = [getattr(mapsys, p) for p in args]

        self.LineEdits=[]
        for i in range(len(args)):
            label = QtGui.QLabel("%s:" % args[i])
            le = QtGui.QLineEdit(self)
            le.setText("%f" % parameters[i])
            self.LineEdits.append(le)          
            
            grid.addWidget(label, i, 0)
            grid.addWidget(le, i, 1)
            
        label = QtGui.QLabel("Priodicity:")
        grid.addWidget(label,i+1,0)
        i = i + 2
        qp = ["q:","p:"]
        self.Combs=[]
        for j in range(2):
            i = i + j
            label = QtGui.QLabel("%s" % qp[j])
            grid.addWidget(label, i, 0)
                        
            combo = QtGui.QComboBox()
            combo.addItems(['True','False'])
            if mapsys.periodicity[j]:
                combo.setCurrentIndex(0)
            else:
                combo.setCurrentIndex(1)                
            self.Combs.append(combo)
            grid.addWidget(combo, i, 1)

        
        self.buttonBox = QtGui.QDialogButtonBox(self)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        #self.buttonBox.clicked.connect(self.actClose)
        self.buttonBox.accepted.connect(self.accept)
        self.buttonBox.rejected.connect(self.close)                

        grid.addWidget(self.buttonBox, i+1,1)
        self.setLayout(grid)
        self.setWindowTitle('Parameter Setting')
        
    def accept(self):
        self.paras = [float(x.text()) for x in self.LineEdits]
        self.periodicity = [True if x.currentText() == 'True' else False for x in self.Combs]
        self.close()
        


class DesignerMainWindow(QtGui.QMainWindow, Ui_MainWindow):
    """Customization for Qt Designer created window"""
    def __init__(self, parent = None):
        super(DesignerMainWindow, self).__init__(parent)

        # setup the GUI --> function generated by pyuic4
        self.setupUi(self)
        self.creatActions()
        self.SelectMapping()

        # mapy
        self.mapsys = mapy.Systems.Standard()
        self.mapsys = getattr(mapy.Systems, "Standard")()

    def creatActions(self):
        #signal slot
        self.plotButton.clicked.connect(self.actPlot)
        self.canvasClearButton.clicked.connect(self.actCanvasClear)
        self.ReplotButton.clicked.connect(self.actReplot)        
        self.mpl.canvas.mpl_connect('button_press_event', self.actCanvasPress)
        self.mpl.canvas.mpl_connect('button_release_event', self.actCanvasRelease)        
        self.mpl.canvas.mpl_connect('mouse', self.actCanvasPress)        
        self.mpl.canvas.mpl_connect('mouse', self.actCanvasRelease)                
        
        self.actionAboutQtMapy.triggered.connect(self.on_AboutInfomation)
        self.dialogTextBrowser = AboutDialog()
        self.ParameterButton.clicked.connect(self.openParameterSettingDialog)        

        # grouping
        self.MappingGroup = QtGui.QActionGroup(self)
        self.MappingGroup.addAction(self.actionHenon_map)
        self.MappingGroup.addAction(self.actionStandard_map)
        self.MappingGroup.addAction(self.actionHarper_map)
        self.MappingGroup.addAction(self.actionHarmonic_map)
        self.MappingGroup.triggered.connect(self.SelectMapping)
        
        self.actionEnergy_contour.triggered.connect(self.plot_energy_contour)


    def SelectMapping(self):
        # map select
        mapping = self.MappingGroup.checkedAction()
        sysname = mapping.text().split(" ")[0]
        self.mapsys = getattr(mapy.Systems, sysname)()
        self.show_system_def(sysname, self.label_SystemInfo)
        self.show_system_parameter(self.label_Parameters)
        self.parameterDialog = ParameterDialog(self.mapsys)              

    """ system infomation """
    def openParameterSettingDialog(self):
        self.parameterDialog.exec_()
        paras = self.parameterDialog.paras
        periodicity = self.parameterDialog.periodicity
        mapping = self.MappingGroup.checkedAction()        
        sysname = mapping.text().split(" ")[0]
        f = getattr(mapy.Systems, sysname)
        self.mapsys = f(*paras)
        self.mapsys.periodicity = periodicity
        self.show_system_parameter(self.label_Parameters)    
    def show_system_def(self, sysname,label):
        q,p = sympy.Symbol("q"),sympy.Symbol("p")
        args = inspect.getargspec(self.mapsys.__init__)[0][1:]
        paras = [sympy.Symbol(p) for p in args]
        f = getattr(mapy.Systems, sysname)
        mapsys = f(*paras)
        T, V = mapsys.get_Hamiltonian()
        kinetic_info = "T(q,p) = %s" % T(p)
        potential_info = "V(q,p) = %s" % V(q)
        sysinfo = kinetic_info + "\n" + potential_info
        label.setText("%s" % sysinfo)

    def show_system_parameter(self, label):
        args = inspect.getargspec(self.mapsys.__init__)[0][1:]
        paras = [getattr(self.mapsys, p) for p in args]
        parainfo = ""
        for i in range(len(args)):
            parainfo += "%s = %f\n"  % (args[i], paras[i])
        label.setText("%s" % parainfo)
        self.show_system_periodicity(self.label_Periodicity)                

    def show_system_periodicity(self,label):
        p = self.mapsys.periodicity
        text = "q: %s\t p:%s" % (p[0],p[1])
        label.setText("%s"% text)
        
    
    """ menu """
    def on_AboutInfomation(self):
        self.dialogTextBrowser.exec_()

    """ mpl setting """
    def set_mpl_canvas_plot_range(self):
        """
        x = self.lineEdit_qrange.text().split(",")
        y = self.lineEdit_prange.text().split(",")

        pr_str = [x[0].strip(),x[1].strip(), y[0].strip(),y[1].strip()]
        pr = []        
        for z in pr_str:
            pr.append(float(sympy.N(z)))
        """
        x = self.decode_str2float(self.lineEdit_qrange.text())
        y = self.decode_str2float(self.lineEdit_prange.text())        
        self.mpl.canvas.ax.set_xlim(x[0],x[1])
        self.mpl.canvas.ax.set_ylim(y[0],y[1])
        return [x,y]
        
    def actCanvasRelease(self, event):
        if not self.checkBoxClickable.isChecked():
            return
        elif self.comboBox_Select_Init.currentText() in ['linear', 'box']:
            q0 = self.decode_str2float(self.lineEdit_q.text())[0]
            p0 = self.decode_str2float(self.lineEdit_p.text())[0]
            q1,p1 = event.xdata, event.ydata
            self.lineEdit_q.setText("%f,%f" % (q0,q1))
            self.lineEdit_p.setText("%f,%f" % (p0,p1))

    def actCanvasPress(self, event):
        if not self.checkBoxClickable.isChecked():
            return
        try:
            print('(x,y) = (%f, %f) :button=%d, '% (event.xdata, event.ydata, event.button))
            self.lineEdit_q.setText("%f" % event.xdata)
            self.lineEdit_p.setText("%f" % event.ydata)
            init = [np.array([event.xdata]), np.array([event.ydata])]
            
        except TypeError:
            init = None
            return 

        if self.comboBox_Select_Init.currentText() == 'point':                
            iteration = int(self.itaration_lineEdit.text())
            dt = float(self.lineEdit_SI_dt.text())
            order = int(self.lineEdit_SI_order.text())                        
            mapping = Mapping(self.mapsys, dt, order)
            x = mapping.iterate(init, iteration)
            self.mpl.canvas.ax.plot(x[0],x[1],',')
            self.mpl.canvas.draw()                            
        
        
    def actReplot(self):     
        self.set_mpl_canvas_plot_range()    
        self.mpl.canvas.draw()

    def actCanvasClear(self):
        self.mpl.canvas.ax.clear()
        self.mpl.canvas.draw()
        
    def plot_energy_contour(self):
        xr = self.set_mpl_canvas_plot_range()
        q = np.linspace(xr[0],xr[1])
        p = np.linspace(xr[2],xr[3])
        q, p = np.meshgrid(q,p)
        T,V = self.mapsys.get_Hamiltonian()
        H = T(p) + V(q)
        levels = np.linspace(H.min(), H.max(), 30)
        self.mpl.canvas.ax.contour(q,p,H,levels)
        self.mpl.canvas.draw()
        

    """ others """
    def decode_str2float(self, text):
        strs = text.split(",")
        xstrs = [x.strip() for x in strs]
        x = []
        for y in xstrs:
            x.append(float(sympy.N(y)))
        return x
        
    
    def actPlot(self):
        dt = float(self.lineEdit_SI_dt.text())
        order = int(self.lineEdit_SI_order.text())
        mapping = Mapping(self.mapsys, dt, order)
        iteration = int(self.itaration_lineEdit.text())
        samplenum = int(self.samplenum_lineEdit.text())         
                   
        if self.comboBox_Select_Init.currentText() == 'point':
            q0 = self.decode_str2float(self.lineEdit_q.text())
            p0 = self.decode_str2float(self.lineEdit_p.text())
            init = [np.array(q0), np.array(p0)]
            x = mapping.iterate(init, iteration)

        elif self.comboBox_Select_Init.currentText() == 'random':        
            x = mapping.random_iterate(iteration, samplenum)

        elif self.comboBox_Select_Init.currentText() == 'linear':
            xr = self.decode_str2float(self.lineEdit_q.text())
            yr = self.decode_str2float(self.lineEdit_p.text())
#            xmin, xmax = (q0[0], q0[1]) if q0[0] < q0[1] else (q0[1], q0[0])
#            ymin, ymax = (p0[0], p0[1]) if p0[0] < p0[1] else (p0[1], p0[0])
            if np.abs(xr[1] - xr[0])<=1e-16:
                x = np.array([0.0]*samplenum)
                y = np.linspace(yr[0], yr[1], samplenum)
            else:
                a = (yr[1] - yr[0])/(xr[1] - xr[0])
                x = np.linspace(xr[0],xr[1], samplenum)
#                ymin = yr[0] if yr[0] < yr[1] else yr[1]
#                xmin = xr[0] if xr[0] < xr[1] else xr[1]
                y = a*(x - xr[0]) + yr[0]
            init = [x,y]
            x = mapping.iterate(init, iteration)
        else:
            x = [None, None]
                        
        self.mpl.canvas.ax.plot(x[0],x[1],',')
        self.mpl.canvas.draw()            
        

        
        
            
def run():
    app = QtGui.QApplication(sys.argv)
    dmw = DesignerMainWindow()
    dmw.show()
    sys.exit(app.exec_())
    

